name: Mutation Tests

on:
  push:
    branches:
      - "main"
    paths:
      - ".github/workflows/balance-mutation-testing.yml"
  schedule:
    - cron: "30 3 * * 1-5"
  workflow_dispatch:

permissions:
  contents: write

concurrency:
  group: 'mutation-testing'
  cancel-in-progress: true

env:
  DOTNET_NOLOGO: 1 # Disable the .NET welcome message
  DOTNET_CLI_TELEMETRY_OPTOUT: 1 # Opt out of the .NET SDK telemetry feature

jobs:
  run-mutation:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          ref: main
          persist-credentials: true
          fetch-depth: 0

      - name: Setup .NET [v10.0.x]
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: 10.0.x

      - name: Install Stryker Globally
        run: |
          dotnet tool install --global dotnet-stryker --version 4.16.0
          echo "$HOME/.dotnet/tools" >> $GITHUB_PATH

      - name: Start MongoDB Container
        run: docker compose -f src/test/IntegrationTest.Infra.MongoDB/docker-compose.yml up -d

      - name: Resolve dependencies
        run: dotnet restore --force --no-cache

      - name: Hack [issue "MSB3026 Unable to copy file" for EmbeddedResources]
        run: |
          mkdir -p src/test/IntegrationTest.EntryPoint.WebApi/bin/Debug/net10.0/{pt-br,en-us}
          mkdir -p src/test/IntegrationTest.EntryPoint.WebApi/bin/Release/net10.0/{pt-br,en-us}

      - name: Build in Debug Mode
        run: dotnet build --configuration Debug --no-restore

      - name: Mutation [Core]
        working-directory: ./src/test/UnitTest.Core
        run: dotnet stryker

      - name: Mutation [EntryPoint WebApi]
        working-directory: ./src/test/IntegrationTest.EntryPoint.WebApi
        run: dotnet stryker

      - name: Mutation [Infra MongoDB]
        working-directory: ./src/test/IntegrationTest.Infra.MongoDB
        run: dotnet stryker

      - name: Gather Reports
        run: |
          mkdir -p ./docs/mutation-reports/Core ./docs/mutation-reports/EntryPoint.WebApi ./docs/mutation-reports/Infra.MongoDB
          find ./src/test/UnitTest.Core/StrykerOutput -name '*.html' -exec cp -prv '{}' './docs/mutation-reports/Core' ';' || true
          find ./src/test/IntegrationTest.EntryPoint.WebApi/StrykerOutput -name '*.html' -exec cp -prv '{}' './docs/mutation-reports/EntryPoint.WebApi' ';' || true
          find ./src/test/IntegrationTest.Infra.MongoDB/StrykerOutput -name '*.html' -exec cp -prv '{}' './docs/mutation-reports/Infra.MongoDB' ';' || true

      - name: Commit and Push Changes
        run: |
          if [ -n "$(git status --porcelain)" ]; then
            git config pull.rebase false        
            git config --local user.email "action@github.com"
            git config --local user.name "Stryker.NET"
            git add docs/mutation-reports/
            git commit -m "doc(testing): update mutation reports"
            git pull origin main
            git push origin main
          else
            echo "No changes to commit"
          fi

      - name: Environment Teardown
        if: always()
        run: docker compose -f src/test/IntegrationTest.Infra.MongoDB/docker-compose.yml down
